# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook.proto',
  package='addressbook',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11\x61\x64\x64ressbook.proto\x12\x0b\x61\x64\x64ressbook\"\xf1\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x12\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12/\n\x06phones\x18\x04 \x03(\x0b\x32\x1f.addressbook.Person.PhoneNumber\x12\x14\n\x0clast_updated\x18\x05 \x02(\t\x1aJ\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x02(\t\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x1d.addressbook.Person.PhoneType\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"#\n\x13\x41\x64\x64ressBookGetQuery\x12\x0c\n\x04name\x18\x01 \x02(\t\"$\n\x16\x41\x64\x64ressBookDeleteQuery\x12\n\n\x02id\x18\x01 \x02(\x12\"\x11\n\x02Ok\x12\x0b\n\x03msg\x18\x01 \x02(\t2\xf2\x01\n\x0b\x41\x64\x64ressBook\x12@\n\x03Get\x12 .addressbook.AddressBookGetQuery\x1a\x13.addressbook.Person\"\x00\x30\x01\x12\x30\n\x06Update\x12\x13.addressbook.Person\x1a\x0f.addressbook.Ok\"\x00\x12-\n\x03Set\x12\x13.addressbook.Person\x1a\x0f.addressbook.Ok\"\x00\x12@\n\x06\x44\x65lete\x12#.addressbook.AddressBookDeleteQuery\x1a\x0f.addressbook.Ok\"\x00'
)



_PERSON_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='addressbook.Person.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=233,
  serialized_end=276,
)
_sym_db.RegisterEnumDescriptor(_PERSON_PHONETYPE)


_PERSON_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='addressbook.Person.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='addressbook.Person.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='addressbook.Person.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=231,
)

_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='addressbook.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='addressbook.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='addressbook.Person.id', index=1,
      number=2, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='addressbook.Person.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phones', full_name='addressbook.Person.phones', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_updated', full_name='addressbook.Person.last_updated', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_PHONENUMBER, ],
  enum_types=[
    _PERSON_PHONETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=276,
)


_ADDRESSBOOKGETQUERY = _descriptor.Descriptor(
  name='AddressBookGetQuery',
  full_name='addressbook.AddressBookGetQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='addressbook.AddressBookGetQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=313,
)


_ADDRESSBOOKDELETEQUERY = _descriptor.Descriptor(
  name='AddressBookDeleteQuery',
  full_name='addressbook.AddressBookDeleteQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='addressbook.AddressBookDeleteQuery.id', index=0,
      number=1, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=351,
)


_OK = _descriptor.Descriptor(
  name='Ok',
  full_name='addressbook.Ok',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='addressbook.Ok.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=370,
)

_PERSON_PHONENUMBER.fields_by_name['type'].enum_type = _PERSON_PHONETYPE
_PERSON_PHONENUMBER.containing_type = _PERSON
_PERSON.fields_by_name['phones'].message_type = _PERSON_PHONENUMBER
_PERSON_PHONETYPE.containing_type = _PERSON
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['AddressBookGetQuery'] = _ADDRESSBOOKGETQUERY
DESCRIPTOR.message_types_by_name['AddressBookDeleteQuery'] = _ADDRESSBOOKDELETEQUERY
DESCRIPTOR.message_types_by_name['Ok'] = _OK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'PhoneNumber' : _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_PHONENUMBER,
    '__module__' : 'addressbook_pb2'
    # @@protoc_insertion_point(class_scope:addressbook.Person.PhoneNumber)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.PhoneNumber)

AddressBookGetQuery = _reflection.GeneratedProtocolMessageType('AddressBookGetQuery', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSBOOKGETQUERY,
  '__module__' : 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.AddressBookGetQuery)
  })
_sym_db.RegisterMessage(AddressBookGetQuery)

AddressBookDeleteQuery = _reflection.GeneratedProtocolMessageType('AddressBookDeleteQuery', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSBOOKDELETEQUERY,
  '__module__' : 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.AddressBookDeleteQuery)
  })
_sym_db.RegisterMessage(AddressBookDeleteQuery)

Ok = _reflection.GeneratedProtocolMessageType('Ok', (_message.Message,), {
  'DESCRIPTOR' : _OK,
  '__module__' : 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.Ok)
  })
_sym_db.RegisterMessage(Ok)



_ADDRESSBOOK = _descriptor.ServiceDescriptor(
  name='AddressBook',
  full_name='addressbook.AddressBook',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=373,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='addressbook.AddressBook.Get',
    index=0,
    containing_service=None,
    input_type=_ADDRESSBOOKGETQUERY,
    output_type=_PERSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='addressbook.AddressBook.Update',
    index=1,
    containing_service=None,
    input_type=_PERSON,
    output_type=_OK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='addressbook.AddressBook.Set',
    index=2,
    containing_service=None,
    input_type=_PERSON,
    output_type=_OK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='addressbook.AddressBook.Delete',
    index=3,
    containing_service=None,
    input_type=_ADDRESSBOOKDELETEQUERY,
    output_type=_OK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDRESSBOOK)

DESCRIPTOR.services_by_name['AddressBook'] = _ADDRESSBOOK

# @@protoc_insertion_point(module_scope)
