# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: addressbook.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import addressbook_pb2


class AddressBookBase(abc.ABC):

    @abc.abstractmethod
    async def Get(self, stream: 'grpclib.server.Stream[addressbook_pb2.AddressBookGetQuery, addressbook_pb2.Person]') -> None:
        pass

    @abc.abstractmethod
    async def Update(self, stream: 'grpclib.server.Stream[addressbook_pb2.Person, addressbook_pb2.Ok]') -> None:
        pass

    @abc.abstractmethod
    async def Set(self, stream: 'grpclib.server.Stream[addressbook_pb2.Person, addressbook_pb2.Ok]') -> None:
        pass

    @abc.abstractmethod
    async def Delete(self, stream: 'grpclib.server.Stream[addressbook_pb2.AddressBookDeleteQuery, addressbook_pb2.Ok]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/addressbook.AddressBook/Get': grpclib.const.Handler(
                self.Get,
                grpclib.const.Cardinality.UNARY_STREAM,
                addressbook_pb2.AddressBookGetQuery,
                addressbook_pb2.Person,
            ),
            '/addressbook.AddressBook/Update': grpclib.const.Handler(
                self.Update,
                grpclib.const.Cardinality.UNARY_UNARY,
                addressbook_pb2.Person,
                addressbook_pb2.Ok,
            ),
            '/addressbook.AddressBook/Set': grpclib.const.Handler(
                self.Set,
                grpclib.const.Cardinality.UNARY_UNARY,
                addressbook_pb2.Person,
                addressbook_pb2.Ok,
            ),
            '/addressbook.AddressBook/Delete': grpclib.const.Handler(
                self.Delete,
                grpclib.const.Cardinality.UNARY_UNARY,
                addressbook_pb2.AddressBookDeleteQuery,
                addressbook_pb2.Ok,
            ),
        }


class AddressBookStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Get = grpclib.client.UnaryStreamMethod(
            channel,
            '/addressbook.AddressBook/Get',
            addressbook_pb2.AddressBookGetQuery,
            addressbook_pb2.Person,
        )
        self.Update = grpclib.client.UnaryUnaryMethod(
            channel,
            '/addressbook.AddressBook/Update',
            addressbook_pb2.Person,
            addressbook_pb2.Ok,
        )
        self.Set = grpclib.client.UnaryUnaryMethod(
            channel,
            '/addressbook.AddressBook/Set',
            addressbook_pb2.Person,
            addressbook_pb2.Ok,
        )
        self.Delete = grpclib.client.UnaryUnaryMethod(
            channel,
            '/addressbook.AddressBook/Delete',
            addressbook_pb2.AddressBookDeleteQuery,
            addressbook_pb2.Ok,
        )
